import type { Metadata } from "next";
import { Fira_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { AppleStyleDock } from "@/components/home/dock-navbar";
import { Toaster } from "@/components/ui/sonner";

const firaCode = Fira_Mono({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${firaCode.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
          <main className="max-w-5xl px-4 min-h-screen mx-auto">
            {children}
            <AppleStyleDock />
          </main>

          <Toaster position="top-center" />
        </ThemeProvider>
      </body>
    </html>
  );
}
